### ISSUE TITLE
Meshlab bugging about upgrading

### ISSUE THREAD

**Issue by oleg-alexandrov** [cnr-isti-vclab/meshlab#550] opened 2020-01-10 03:50 UTC
Every day I get a pop-up asking to upgrade to the latest version. Ironically, I actually run the latest build, and I am told to upgrade to the "new" 2016 version. 

And this bug can't be fixed, since the logic happens on http://vcg.isti.cnr.it/ to which meshlab tells my build version (2020.1) and which decides magically that my version is older than 2016.

**Comment by martin-frbg** [comment] 2020-01-10 12:53
Probably a duplicate of "critical bug" #328

**Comment by oleg-alexandrov** [comment] 2020-01-10 19:04
I added a pull request at https://github.com/cnr-isti-vclab/meshlab/pull/552

**Closed** 2020-01-13 16:44 UTC
