### ISSUE TITLE
Freeze Loading .obj

### ISSUE THREAD

**Issue by Kneesnap** [cnr-isti-vclab/meshlab#599] opened 2020-03-13 00:04 UTC
Upon loading the obj attached below, meshlab freezes / becomes unusable.

[GEN_FROG.zip](https://github.com/cnr-isti-vclab/meshlab/files/4327169/GEN_FROG.zip)

**Comment by rpavlik** [comment] 2020-03-25 15:46
It opens for me, on Linux with master + some local patches, as well as with 2020.03, though it looks a little unexpected:

![image](https://user-images.githubusercontent.com/61129/77555880-c733fc00-6e85-11ea-86cb-8cd35cf4d980.png)

Are you on macOS by chance? If so, this might be a dupe of #584

**Comment by Kneesnap** [comment] 2020-03-25 18:06
I'm on Windows.

**Comment by potenziani** [comment] 2020-03-27 11:49
It opens for me, on Windows 10 and MeshLab 2020.02 (and 2020.03). 
But, as @rpavlik points out, there is something wrong with the mesh (not rare exporting/importing obj format between different programs), and MeshLab freezes if you switch texture on/off.

As usual, the advice is to open the mesh and then re-export it with MeshLab. 

Here the result (left, the original file; right, the same file re-exported with MeshLab):

![Annotazione 2020-03-27 122455](https://user-images.githubusercontent.com/2982503/77752777-7f010f00-7028-11ea-9860-132d52c1c8c2.png)

With the re-exported file MeshLab should no longer crash. Try it and let us know.

**Comment by rpavlik** [comment] 2020-03-27 15:46
In case you don't have any machine that can open that file without crashing, I've re-exported it locally here.
[GEN_FROG_resaved.zip](https://github.com/cnr-isti-vclab/meshlab/files/4394507/GEN_FROG_resaved.zip)

A bit weird why you're seeing a freeze we can't reproduce...

**Comment by Kneesnap** [comment] 2020-03-28 00:06
I'm able to load the resaved model just fine.

Unfortunately, that model is not entirely correct.

This model was ripped from a game, and that ball thing near his mouth is the Frog's throat.
The game expands and contracts that area when Frogger "croaks".

Unfortunately the problem is what the program that exported this model seems to be following the .obj specification to the letter.

I should mention I'm using 2016.02, but only because newer versions won't even open on my computer for some reason.

**Comment by Kneesnap** [comment] 2020-03-28 00:07
Getting a model that opens in meshlab isn't really my goal here, it's to make my program able to export models that MeshLab can open.

**Comment by potenziani** [comment] 2020-03-30 17:07
Unfortunately obj format importer/exporter change a lot from program to program, and to find a viable solution for all is not so easy (here it is another recent issue on the same wavelength https://github.com/cnr-isti-vclab/meshlab/issues/409).

Ps: for your issue with the latest MeshLab version take a look at https://github.com/cnr-isti-vclab/meshlab/issues/595#event-3110794746

**Comment by Kneesnap** [comment] 2020-04-01 18:39
@potenziani You're right, there is a lot of difficulty because of all of the different implementations of .obj file handling. That doesn't mean there aren't things that can be done though. For instance, instead of just having MeshLab freeze forever, it would be awesome if it had a pop up with an error message that had at least a brief description of the problem. (Weirdly one of the issues you linked has a screenshot of something that looks like this. However, I have never had an error pop up like for me.)

**Closed** 2020-07-03 20:44 UTC
Labels: wontfix
