### ISSUE TITLE
gLTF Import with more than one texture

### ISSUE THREAD

**Issue by mikeucfl** [cnr-isti-vclab/meshlab#1193] opened 2022-01-19 06:06 UTC
I'm using MeshLab 2021.10d in Windows and am having issues loading a gLTF model that has more than one texture. I created a sample cube with 3 textures (red, green, and blue), however only the red texture seems to be applied to the model.

I've tried to trace through the software and do see different texture IDs being assigned here https://github.com/cnr-isti-vclab/meshlab/blob/master/src/meshlabplugins/io_gltf/gltf_loader.cpp#L631, and also saw each texture used in a glBindTexture call in https://github.com/cnr-isti-vclab/meshlab/blob/master/src/common/ml_shared_data_context/ml_scene_gl_shared_data_context.cpp#L203. I however didn't see any glActiveTexture calls to swap to the other textures, but I assume there's another call being made to do that as the obj version of this model does load properly and doesn't call glActiveTexture.

Anyone have some ideas where to look, or know what's up?
[cube.zip](https://github.com/cnr-isti-vclab/meshlab/files/7894475/cube.zip)

**Comment by mikeucfl** [comment] 2022-01-19 20:44
I am not entirely sure my fixes are appropriate, but I have resolved the issue I had here https://github.com/cnr-isti-vclab/meshlab/pull/1194

**Comment by alemuntoni** [comment] 2022-01-20 08:20
I am not sure that your PR is solving the issue.
If I load your file example in an online gltf viewer (e.g. [here](https://gltf-viewer.donmccurdy.com/)), I can see that the cube has two faces for each color. This does not happen with the solution you proposed: it shows four blue faces, one red and one green.

From what I remember of the gltf format there was support just for vertex texture coordinates, am I wrong?
Btw, in the file you shared, the online gltf viewer reports 12 errors. Could they be part of the cause of this issue? I really don't know how tinygltf manages these errors.

**Comment by mikeucfl** [comment] 2022-01-20 17:09
Ah, crap. Good catch. I was testing a different model that I'm not allowed to share, and it was working fine for that one. When I looked back at the cube model I saw the 3 colors, and didn't thoroughly check all the faces. 

The issue that I was trying to get around was that vcglib seems to not want to render more than one texture when using vertex textures, only for wedge textures. https://github.com/cnr-isti-vclab/vcglib/blob/5cdefce22e377369d7c8eede0c78a6fb224b81de/wrap/gl/gl_mesh_attributes_multi_viewer_bo_manager.h#L990 assigns all faces to the first texture (0) in chunkmap, and if using wedge textures it would be filled out with more than one texture if applicable. Textures are then set later on via iteration of _texindnumtriangles, which was populated with data from the chunkmap. I'll study this code more to see if there's another way.

As far as the errors in the cube, they were related to setting incorrect max values for min/max, and an unused object. Attached is the updated model that should have no more errors, but still have the issue I'm describing.

[cube-no-errors.zip](https://github.com/cnr-isti-vclab/meshlab/files/7907151/cube-no-errors.zip)

**Comment by mikeucfl** [comment] 2022-01-20 22:06
I believe I figured the issue where there were 1/1/4 (rgb) squares vs 2/2/2, and just made a commit. in gltf_loader.cpp, textureImg was always being reassigned to the last texture, even if the texture already existed (addTexture silently exits because the texture name was found). 

I also looked more into the gl_mesh_attributes_multi_viewer_bo_manager and saw an alternate rendering method drawTrianglesIM which also talks about using only one texture when using per vertex texture coordinates https://github.com/cnr-isti-vclab/vcglib/blob/5cdefce22e377369d7c8eede0c78a6fb224b81de/wrap/gl/gl_mesh_attributes_multi_viewer_bo_manager.h#L1559. With what I've seen in this class, it seems using wedge textures is appropriate fix here? However I'll admit, I'm not too familiar with the concept of a wedge texture.. I'm just assuming it's a texture for some polygon type (so I could still be wrong in this implementation even if it's rendering correctly).

**Comment by alemuntoni** [comment] 2022-01-21 11:15
Ok, I looked in depth all the situation, and I'm sorry but I can't accept the PR. The reason is that it is not solving the real problem, of this shape, that I'm pretty sure it is the same reported in #870.
Also in this shape, texture ids are assigned correctly. You can check them by using the "info" tool: for each vertex, there is written (for example) `[V]uv(1 1) id: 1`. `id` is the id of the texture associated to the texture coordinate, and as you can see in the various faces of the cube, they are correct! Therefore, the data structure of the mesh stores all the info correctly, but then they are not rendered correctly. And therefore, the issue is **not** on the gltf loader, but in the GL rendering. 
I need to investigate more on why this is happening (that portions of code are still kind of misteorios to me)...

**Comment by mikeucfl** [comment] 2022-01-21 14:48
I do not see the same thing you do when viewing the texture IDs, without these changes the texture ids are always 0. Here's some before and after screenshots of what I'm seeing, is this not what you see?
![texture_issue_1](https://user-images.githubusercontent.com/8254157/150544869-7799eeda-8ff8-4b35-9a4d-0b5af545b11f.png)
![texture_issue_2](https://user-images.githubusercontent.com/8254157/150544870-64c1fd78-81b9-4681-a10c-cb0ff6ea8649.png)

As far as the rendering code, hopefully what I found helps you investigate the issue when you have time. From everything I can see, it wants to force one texture id when using vertex textures. I'm not even sure this is appropriate for glTF models too, since texture ids are assigned at the mesh primitive level, and not per vertex (see https://www.khronos.org/registry/glTF/specs/2.0/glTF-2.0.html#meshes-overview where they assign a material per primitive)

**Comment by mikeucfl** [comment] 2022-01-21 15:01
Also I just took a brief look at https://github.com/cnr-isti-vclab/meshlab/issues/870 and that issue is different than what I'm seeing, but is a rendering issue I think. The fillchunkMap() code iterates the faces and assigns _chunkmap with a texture id key and the range of faces which are associated with that texture id. There are 3 faces in that model (test4.obj), 2 with texture id 0, and 1 with texture id 1. The conditional check for if the texture id has changed, contains a additional check for if it's the last face. In this case the last face 
 has a different texture id, and this forces all 3 faces to use the first texture. See https://github.com/cnr-isti-vclab/vcglib/blob/5cdefce22e377369d7c8eede0c78a6fb224b81de/wrap/gl/gl_mesh_attributes_multi_viewer_bo_manager.h#L2127 for what I'm describing.

**Comment by alemuntoni** [comment] 2022-01-21 15:22
Sorry, I was testing the old cube having the errors!
With the new adjusted cube, actually the ids are always 0. But the error can be fixed just applying the "second patch" of your PR (the portion of code that avoids to reassign textureImg always to the last texture).  Just applying that one (or commenting the parts where you add wedge texcoords), texture ids are correct (but the rendering not). Therefore I was wrong, there was a bug also in the gltf loader :)

Let me know if this makes sense to you!
This is my patch to your pr: [mypatch.zip](https://github.com/cnr-isti-vclab/meshlab/files/7914758/mypatch.zip)

> Also I just took a brief look at #870 and that issue is different than what I'm seeing, but is a rendering issue I think. The fillchunkMap() code iterates the faces and assigns _chunkmap with a texture id key and the range of faces which are associated with that texture id. There are 3 faces in that model (test4.obj), 2 with texture id 0, and 1 with texture id 1. The conditional check for if the texture id has changed, contains a additional check for if it's the last face. In this case the last face
> has a different texture id, and this forces all 3 faces to use the first texture. See https://github.com/cnr-isti-vclab/vcglib/blob/5cdefce22e377369d7c8eede0c78a6fb224b81de/wrap/gl/gl_mesh_attributes_multi_viewer_bo_manager.h#L2127 for what I'm describing.

It could be a different issue, you're right. I'll try to figure out how to fix it...

**Comment by mikeucfl** [comment] 2022-01-21 15:39
Yes I agree that the "second patch" is what fixes the texture index issue, the "first patch" was the way I got rendering to work (again only used wedge textures because they're the ones that support more than one texture in the render code). 

Just another question too, does it even make sense to assign a texture id per vertex without using a shader? I am not sure a blending of textures would happen without one, which is maybe why the render code forces one texture here. Also could you please explain what a wedge texture is to me, or point me to some google search? I'm not sure I'm finding the correct things when researching it. Is it just a geometry type of 3 or more vertices (e.g. triangle/quad)?

**Comment by alemuntoni** [comment] 2022-01-21 16:01
Here there is an explanation of what a wedge is: https://stackoverflow.com/questions/61724879/what-does-wedge-means-in-vcglib
We can say that they are a way to treat vertices independently for each face, even if they are shared between faces!

> does it even make sense to assign a texture id per vertex without using a shader?

I actually don't know, I am discovering that it is completely ignored in rendering just now... For some reason I always assumed they were managed in some way also when rendered. I'll try to figure out how to manage them...

**Comment by mikeucfl** [comment] 2022-01-21 16:25
Ahh ok that makes sense, thanks for the link. Look forward to seeing what you come up with to address this issue. Thanks!

**Comment by alemuntoni** [comment] 2022-02-01 09:13
Thinking about this, I concluded that for now we just want this working as expected (at least visually) for the next release, which will be out this month. 
Since vertex texture coords  in meshlab supports only one texture per mesh in visualization, I think that the best solution is assuming that gltf only stores per wedge texture coordinates (and therefore don't store vertex texcoords). This is not the ideal solution of course, but at least is a workaround.
@mikeucfl if it is ok for you, I would modify your PR in order to remove vertex texcoords after the mesh is loaded, leaving only wedge texcoords!

**Comment by mikeucfl** [comment] 2022-02-02 02:58
@alemuntoni sounds good to me. Just to be clear, do you mean after loadMeshes has completed.. somewhere there a call to remove the vertex coordinates would occur? Or does this mean a modification to populateVTextCoords so that it stores the wedge textcoords instead (and change the method name to include WT vs V)?

**Comment by alemuntoni** [comment] 2022-02-03 11:25
The latter strategy would be more elegant, but given that we are loading a new model, the code of the load process is quite complex and there is at least the need to have a new parameter used only on this specific case to pass to all the involved functions, I think that we could keep things simple and go with the first strategy you proposed!

**Comment by alemuntoni** [comment] 2022-02-03 12:03
@mikeucfl  I pushed the mod in your PR. Let me know if looks fine to you and then I can merge it!

**Comment by mikeucfl** [comment] 2022-02-03 16:35
@alemuntoni The fix looks good to me. Also tested my use cases and they still work. Thanks!

**Comment by alemuntoni** [comment] 2022-02-03 16:55
Great! Thanks for the contribution @mikeucfl! :)

**Closed** 2022-02-03 16:55 UTC
Labels: confirmed
