### ISSUE TITLE
MeshLabServer taking over cmd.exe link in Windows 10

### ISSUE THREAD

**Issue by andyred3d** [cnr-isti-vclab/meshlab#145] opened 2017-05-02 12:29 UTC
If I type cmd and cmd.exe in Windows 10 search bar it starts a command prompt window called MeshLabServer, with the prompt already set at C;\Program Files\VCG\Meshlab>_

This is really irritating as I use the cmd shortcut in Windows search quite a lot, whereas I am unlikely to ever use the Meshlab server, and I can't seem to find a way to set this back to the default without uninstalling Meshlab. So questions are:

a) Please can someone tell me how to fix this?
b) Can Meshlab fix this permanently so next time it's installed I don;t have to remember how to set it back again.

Many thanks!

**Comment by mcallieri** [comment] 2017-05-02 12:52
I saw it too. 
Seems to me that it happened only recently, and not after installing MeshLab few months ago. It may have been triggered by a recent windows update.
We will look into it.

**Comment by andyred3d** [comment] 2017-05-02 14:00
Thanks Marco, I look forward to your response.

**Comment by gabriel0689** [comment] 2017-05-28 15:34
having the same issue here. 
please look into this, its really annoying.

**Comment by potenziani** [comment] 2017-05-28 18:49
Hi, same issue, this is my workaround (it isn't a final solution, but waiting for the MeshLab fixing, it works to bypass the problem... at least for me). 

Option 1: the issue affects the "cmd.exe" file in "Windows\System32" folder. But if you go o that folder and run the console from there (double click on "cmd.exe" icon), the program runs without the MeshLabServer hijacking. So, my workaround consists in creating a desktop shortcut to this file (right click on "cmd.exe" icon, the send to the Desktop option). Now, you should have your desktop shortcut to use avoiding  MeshLabServer. Please note that the same workaround doesn't work if you try to add "cmd.exe" (or its shortcut) to the Start menu.

Option 2: If you want to add the win console to your Start menu, and you have a 64 bit OS, you can use this same workaround, but this time pointing to the "cmd.exe" file in the "Windows\SysWOW64" folder. Here you have the same  "cmd.exe" file, but without MeshLabServer hijacking, so you can add a desktop shortcut to this file or add it to the Start menu as you prefer, without drawbacks.

Bonus trick: once created your desktop shortcut, if you want to set a default folder to reach every time you run it, you can follow these steps:
1 - open the shortcut properties window (right click on the shortcut icon, and then “Properties”)
2 - in the shortcut properties window, look for the shortcut “target” text field and ADD to the end of the original string this string (a blank space is required between the existing string and the one you are adding):
 /K "cd C:\Users\"
Of course, you can replace "C:\Users\" with the folder that you prefer.

PS: I have noticed this "bug" acts on different devices with the same OS (win 10) in different ways, so the good result of this workaround isn't 100% guarateed... Good luck ;-)

**Comment by mcallieri** [comment] 2017-05-31 13:28
The thing happen because we try creating a shortcut to open a command line window in the MeshLab install folder. As we are using cmd.exe, the installer overwrites all other shortcuts to cmd.exe in the start menu.
We are doing some tests, changing way the shortcut is created.

**Comment by agnoam** [comment] 2017-06-25 09:30
i found a solution
this is very easy and simple, just go to start and find the meshlabServer, find the location of the file.
get out to the folder and delete the folder.
after this the cmd will appear again like new.

**Comment by b-morgan** [comment] 2017-08-01 21:05
I don't understand what agnoam is suggesting. My interpretation of his solution would be to effectively remove all of MeshLab's files rendering it unusable.

mcallieri,

Its been a couple of months, are you making any progress on fixing this?

**Comment by HeroofOne** [comment] 2017-08-30 15:42
I'm also having this problem. It's very frustrating. Why would it take over the cmd.exe?

**Comment by BallboyG** [comment] 2017-09-22 12:41
I can see why they have created their own shortcut but it would seem they have inadvertantly overridden the app search system in Start so their shortcut is picked up over the default .exe when doing a text search - Their link runs the genuine cmd.exe but simply gives it a 'start in' location of the Meshlabs server (a rather clunky solution in my opinion!). A workaround is to simply press 'windows'+'R' and type 'CMD.exe' to run the .exe directly. What is concerning though is that I have uninstalled Meshlab and everything went except for this shortcut which I've had to manually delete!...

**Comment by DavidJRobertson** [comment] 2017-09-23 18:59
@b-morgan You need only remove the .lnk shortcut which removes the start menu entry.

**Comment by trenchant7** [comment] 2017-11-23 04:37
@agnoam thanks for the solution. mine worked

**Comment by exe404** [comment] 2018-01-25 17:57
Is there any update to this? It is 2018 now, and still having this issue occur with install of Meshlab.

Please fix!

**Comment by igrokit** [comment] 2018-02-24 09:48
@exe404, you have to remove the MeshLapServer link from the Start Menu manually. 

Those locations are usually here:

%ProgramData%\Microsoft\Windows\Start Menu\Programs
%AppData%\Microsoft\Windows\Start Menu\Programs

In PowerShell, these two commands will give you the exact locations on your system:
[Environment]::GetFolderPath('StartMenu')
[Environment]::GetFolderPath('CommonStartMenu')

Somewhere in the folders beneath the locations above, you should find the link that bothers you. 

Just delete it and the menu is updated and the search will find the original "cmd" again.

Dan

**Comment by b-morgan** [comment] 2018-02-24 16:36
This issue is tagged with "Critical Bug" yet it hasn't been fixed (or if it has, what commit fixed it) and its been over a year since the last release. What is going on with this project?

**Comment by mcallieri** [comment] 2018-02-24 20:11
it is marked critical because it has to be solved. 
We have revided the installer, and should work, now, but still, we are late in creating the release, due to many other stuff that we have to solve. 
Our time ad resources are limited, and we have let too much time pass since the last release. Now, many more things are broken, due to updates to QT, compiler, and Operating Systems (Linux and MacOS, mostly), so we still have work to do. 

We are setting up an automatic building system on appveyor, this should make easier to get regular updates of the installer.

in any case, it is just a WRONG NAME of the link, it is not that we have deleted system32.dll from the pc :)

**Comment by b-morgan** [comment] 2018-02-24 20:35
I understand that it isn’t a very nasty bug and I did see a commit that had “needs testing” in the comment around 8 months ago. I was just surprised that there wasn’t a follow up that the commit fixed (or didn’t fix) the problem and if fixed, the issue could be closed with “fixed in next release”.

 

We’ve already discussed “next release” and I’m happy to see some progress is being made.

**Comment by AndreaNES** [comment] 2018-08-17 06:56
Incurred into this issue, and I quite displeased about it, and particularly displeased that after removing MeshLab my system was still left affected. 

The non-apologetic way of handling the issue by the MeshLab developers in this discussion will make me think very hard before ever installing MeshLab again on any computer.

P.S. I was able to fix it following the advice of igrokit:

In %AppData%\Microsoft\Windows\Start Menu\Programs there was a folder called MeshLab (left there after uninstall) and deleting that folder reverted cmd.exe to its original function.

Thanks igrokit for sharing this advice !

**Comment by lucidBrot** [comment] 2018-08-19 17:46
A solution that avoids modifying MeshLab: 

1. Open start menu and search for "cmd" as usually. MeshLab Server something will show up
2. Right click that > Open Location
3. Copy the link (it should have the normal cmd.exe as target)
4. move one directory level up, create a folder "cmd" and paste the link
5. rename the link to "cmd.lnk"
6. Wait a few minutes for windows to catch up

**Comment by nate-moo** [comment] 2019-05-12 16:20
> If I type cmd and cmd.exe in Windows 10 search bar it starts a command prompt window called MeshLabServer, with the prompt already set at C;\Program Files\VCG\Meshlab>_
> 
> This is really irritating as I use the cmd shortcut in Windows search quite a lot, whereas I am unlikely to ever use the Meshlab server, and I can't seem to find a way to set this back to the default without uninstalling Meshlab. So questions are:
> 
> a) Please can someone tell me how to fix this?
> b) Can Meshlab fix this permanently so next time it's installed I don;t have to remember how to set it back again.
> 
> Many thanks!

I found that if you just back out of the folder and exit in your home folder in the CMD prompt it will remove the hijacking.  I dont know why or if it only works for me but that is how I did it.

**Comment by glostyle** [comment] 2019-05-26 19:50
It's the middle of 2019 and this is still inconveniencing people. How does it take multiple years to fix something so easy?

**Comment by KeenRivals** [comment] 2019-10-30 18:47
I think what is happening is Windows Start search sees "cmd" in the shortcut and shows it, thinking it helps. MeshLab team, if instead of creating a shortcut to cmd.exe like you do, create a mesh-server.bat batch file in the target directory with the contents below and link it, you should be good.

```cmd
start /D %~dp0 cmd /k
```

This says, start cmd and **/k**eep the window open in the **/D**irectory %~dp0, which is the directory the script is in. This will keep the launcher portable so it should work wherever users install it. I'd submit a PR but I don't know where I'd put it or where to modify your build scripts.

**Comment by josegaspar999** [comment] 2019-11-28 16:02
After steps 1 & 2 of  "lucidBrot commented on 19 Aug 2018" (Open Location), I made a copy of the shortcut "MeshLabServer" in the same folder, renamed the copy to "cmd" and **edited the shortcut copy properties to delete the "Shortcut > Start in"**.

**Comment by SelimOzel** [comment] 2019-12-11 00:00
I just deleted their shortcut and then deleted their software. Not even sure why I installed it in the first place.

LucidBrot's advice is solid. Follow their suggestionz.

**Comment by pfoneill** [comment] 2019-12-11 18:49
Having the same issue, in addition the installation of MeshLab screwed with my %SysteRoot%\System32 PATH variables (including PowerShell) effectively rendering my PC useless until I fixed it.
I fixed it by: (1) removing the MeshLab Server shortcut from the Start Menu\Programs folder as mentioned by a few users here and, [(2) manually adding the %SystemRoot%\System32 fodlers back into my PATH variable](https://helpdeskgeek.com/how-to/fix-not-recognized-as-an-internal-or-external-command/).
This needs to be fixed ASAP.

**Comment by varunreja** [comment] 2020-01-04 06:24
Detele this folder
InAppData\Microsoft\Windows\Start Menu\Programs there was a folder called MeshLab.

cmd.exe will be reverted Cheers!!

**Comment by emueyes** [comment] 2020-02-10 23:59
So this critical bug has been here for 3 years? only just found it myself, had a look round, and found that this place that might be the right place to talk.  The only thing that works reliably for me is win+R  then cmd. But I mean, what is going on? Break a UI and leave it for years, despite a lot of user displeasure. There's other ways around this, I've used AutoHotKey for a long time and that really does smooth out the bumpy bits.

So is this a bug being fixed, a bug not being fixed, or not a bug at all? Do the folk at Meshlab think we're all just creatives who don't know what a command prompt is? I speak as a programmer for 30 years and find 3d modelling incredibly fun, having seen software evolve from the 80s, to to 20s. That is joyous, but these same narrow gauge explanators haven't changed.

**Comment by alemuntoni** [comment] 2020-04-08 17:32
In MeshLab 2020.x this problem doesn't exist anymore.

**Closed by alemuntoni** 2020-04-08 17:32 UTC
Labels: critical bug
