### ISSUE TITLE
Meshlab crashes with valid OBJ file

### ISSUE THREAD

**Issue by pdbourke** [cnr-isti-vclab/meshlab#449] opened 2019-05-12 05:25 UTC
[Archive.zip](https://github.com/cnr-isti-vclab/meshlab/files/3169762/Archive.zip)
I attach a valid OBJ file that causes MeshLab to crash.
Every other OBJ reader I have tried works fine.
Happy for a work-around, haven't found one yet.

**Comment by Grimmwicht** [comment] 2019-09-04 11:01
I can confirm the crash, using MeshLab_64bit_fp v2016.12 (built on Mar 7 2017) on Ubuntu 1904.

Console says:
> Mesh is Polygonal!
> Segmentation fault (core dumped)

**Comment by jmespadero** [comment] 2019-12-16 11:59
It is working for me, current version (2019-12 from source) in an Ubuntu Linux  Bionic 18.04 machine.

![image](https://user-images.githubusercontent.com/6451497/70905285-c9272d00-2003-11ea-91a5-72411c6c42f9.png)

**Comment by alemuntoni** [comment] 2020-02-12 16:43
I'll close this issue since it should be fixed with the last PR.
Feel free to open another issue if the problem persists.

**Closed by alemuntoni** 2020-02-12 16:43 UTC
