### ISSUE TITLE
Can not import obj file(Release 2020.12 OSX)

### ISSUE THREAD

**Issue by akira-sasaki** [cnr-isti-vclab/meshlab#956] opened 2021-04-15 09:15 UTC
**Release version: 2020.12
Platform: OSX (macOS Big Sur)**

I can not import the file of obj format.

I select Menu > File > Import Mesh... , and select obj format file.
But obj format file cannot be opened, and the following error occurs.

```
Error details: file format obj not supported
```

**Comment by alemuntoni** [comment] 2021-04-15 09:22
Probably duplicate of #900, the issue has been already solved and it will work in the next meshlab version.
To have this working, you can try one of the last nightlies built by [github actions](https://github.com/cnr-isti-vclab/meshlab/actions) (select MacOS and download the version you prefer).
Please let me know if it works!

**Comment by akira-sasaki** [comment] 2021-04-15 09:24
I renamed the folder of **PlugIns** folder and that solved the problem.

At first, you move Application folder, and select MeshLab icon, and **CTRL + right click **.
When the shortcut menu appears, select **Show package contents**.

So, you open MeshLab folder, you change folder name of **PlugIns**.

_before_
```
Content/PlugIns
```

_after_
```
Content/plugins
```

**Comment by akira-sasaki** [comment] 2021-04-15 09:26
#900 was the same issue, thanks, issue passed.

**Closed** 2021-04-15 09:28 UTC
