### ISSUE TITLE
Bug? Not exactly, it is a fail in STL color (undocumented feature)

### ISSUE THREAD

**Issue by GiovanniSer** [cnr-isti-vclab/meshlab#1007] opened 2021-06-02 23:34 UTC
In Win 10.
I call Meshlab from my CAD job sending a STL parsed reading my 3DFACEs.
In my parser I have implemented a usefull feature. I read the color of the face (or the color declared in the layer) and I send the colored face to Meshlab, that works very fine. Meshlab reads exactly the color (Even if it is difficult to read because STL does not use the standard 24 bytes...) 
This is really helpful for me, because I can easily locate my wrong faces.
But there is a little problem. When I call the "Re-Orient all face coherentely" the colors are lost and the object becomes all black and white :(
I enclose the example of the correct charge, but if I try to orient all the faces (one as you can see is cian brighter because it is upside down), all the colors are lost.
![Clipboard02](https://user-images.githubusercontent.com/67306481/120564686-bd077900-c40b-11eb-9ab3-015e6c3f9b8c.png)

**Comment by alemuntoni** [comment] 2021-06-03 07:16
Hi, could you please share a model file that allows to replicate the issue?

**Comment by GiovanniSer** [comment] 2021-06-03 07:50
0k, ready.
[abl1.zip](https://github.com/cnr-isti-vclab/meshlab/files/6589871/abl1.zip)

Thank!

**Comment by GiovanniSer** [comment] 2021-06-03 07:58
NB: MeshLab is working correctly, if you Re-Orient all face coherentely and you save the result the new STL is good with all his corrrect colors on the faces!
The B&W trouble is in the screen's rendering while you are working. 
Many thanks.

**Comment by alemuntoni** [comment] 2021-06-03 09:46
The issue is related to shading options that change when they shouldn't in 2021.05.
The issue has been already resolved in previous commits. You can try any of the last nightly builds by following [these instructions](https://github.com/cnr-isti-vclab/meshlab/wiki/How-to-intall-the-last-nightly)

**Closed by alemuntoni** 2021-06-03 09:46 UTC

**Comment by GiovanniSer** [comment] 2021-06-03 11:12
Many thanks!
