### ISSUE TITLE
Project window width with minimum width too large

### ISSUE THREAD

**Issue by WurmD** [cnr-isti-vclab/meshlab#548] opened 2020-01-08 16:40 UTC
MeshLab_64bit_fp v2016.12
OS: Windows 10

1. Currently the minimum width of "Project" window starts limited by the layer name size.
2. Currently the minimum width of "Project" window increases when the dropdown of a layer is opened, and does not decrease when the dropdown is closed.

* If a layer has a very large name, the starting minimum width of "Project" window is too large.

* If the filename associated with a layer is very large, when the dropdown of the layer is open, and you alt-tab away and return, the minimum width of the "Project" window becomes too large

**Expected behavior:**

* Be able to reduce "Project" window width to any size
* If "Project" window width increases when a layer's dropdown menu opens, decrease window width when layer's dropdown menu closes

Example file to reproduce issue: https://www.dropbox.com/s/1jwk5edbhby3nsk/manual10asdfghjklsdfghjklsdfghjkldfghjkl%3Bsdfghjkldfghjklsdfghjksdfghjkdfghjk.obj?dl=1

**Comment by alemuntoni** [comment] 2020-06-22 07:42
Duplicate of #140 
Closing.

**Closed by alemuntoni** 2020-06-22 07:42 UTC
Labels: duplicate
