### ISSUE TITLE
Meshlab Crash

### ISSUE THREAD

**Issue by jwzxgy2007** [cnr-isti-vclab/meshlab#848] opened 2020-12-03 10:34 UTC
- [x] Windows
- [ ] Mac OS
- [ ] Linux
- [ ] Every platform

- [ ] bug or unexpected behavior
- [x] crash
- [ ] feature request
- [ ] other (specify...)

The meshlab version is 2020.12, and this crash also happend in 2020.09.
When I load a mesh in meshlab, and click this button to close. When I do it twice, the meshlab is crashed. 
![](https://user-images.githubusercontent.com/14820455/100997992-f3b42200-3595-11eb-9845-ba6ace6ecd32.png)

**Comment by alemuntoni** [comment] 2020-12-03 11:07
Duplicate of #780. I still didn't have time to properly debug this, but I'll do this ASAP!

**Closed** 2020-12-03 11:08 UTC
