### ISSUE TITLE
crash on right click

### ISSUE THREAD

**Issue by christian-rauch** [cnr-isti-vclab/meshlab#809] opened 2020-10-16 15:46 UTC
#### Check all platforms you experienced the issue (change to `[x]`)
- [ ] Windows
- [ ] Mac OS
- [x] Linux
- [ ] Every platform

#### What type of issue is?
- [ ] bug or unexpected behavior
- [x] crash
- [ ] feature request
- [ ] other (specify...)

#### Describe your issue

Meshlab 2020.09 crashes (`Segmentation fault (core dumped)`) when right-clicking in the 3D view. This probably happens with any mesh, for example the `brain.ply` from the official samples.

It does not happen with the 2020.07 snap version.

**Comment by alemuntoni** [comment] 2020-10-16 16:11
Duplicate of #686.
I believe this happens in some graphics cards in linux distros, The segfault happened inside a gl_draw call.
Hard to debug and it is probably related to some graphic drivers bug.

**Comment by christian-rauch** [comment] 2020-10-16 16:33
I overlooked that issue, probably because it is "closed".

The issue is indeed related to the Nvidia prime settings. When the prime setting is either `on-demand` or `intel`, the message `LOG: 1 There are gl errors: invalid operation` appears. A `sudo prime-select nvidia` and reboot switches directly to the dedicated Nvidia card and "solves" the issue for me.

Since this is not the case with the 2020.07 snap version, is this something that was introduced recently? Would it be possible to revert that or work-around it? It's hard to say if this is an application or driver bug.

**Comment by alemuntoni** [comment] 2020-10-16 17:08
I remember that I tested also the 2016.12 with non `prime-select` drivers and the bug was already there, so reverting it would be impossible (I think that in 2016.12 glew 2.1 was introduced, but I'm not sure).
But it is strange that using snap works. It could actually be a glew bug, because AppImages are compiled using the bundled glew library in the meshlab repository, and probably the snap uses the system built-in library.

A possible workaround would be to add an option that disables the selection of the mesh with the right click.

**Comment by christian-rauch** [comment] 2020-10-18 23:19
This is indeed a driver issue with the newer Intel `iris` driver and does not happen with the older `i965` driver. The `iris` driver issue has been reported at https://gitlab.freedesktop.org/mesa/mesa/-/issues/3663.

The older Intel driver can be manually enforced by setting the `MESA_LOADER_DRIVER_OVERRIDE` environment variable to `i965`, e.g. `MESA_LOADER_DRIVER_OVERRIDE=i965 meshlab` will work around this issue on Intel systems.
@alemuntoni Maybe it is useful to document this somewhere so that Intel GPU users can work around this until the original driver issue has been fixed.

**Comment by alemuntoni** [comment] 2020-12-10 13:55
Are there any news about the drivers update? In the meantime, I added a `known_issues.md` file in the `docs` directory pointing to this issue.

**Closed by alemuntoni** 2020-12-10 13:55 UTC

**Comment by christian-rauch** [comment] 2020-12-10 14:11
> Are there any news about the drivers update?

The driver issue has been fixed in `mesa`. But I don't know when this fix will be distributed.

**Comment by alemuntoni** [comment] 2020-12-10 14:12
Great! Let's hope it will be distribute soon!
Thank you!!

**Comment by monajalal** [comment] 2024-04-16 19:17
```
$ sudo apt remove meshlab
$ sudo snap install meshlab
```
Resolved the problem for me.
