### ISSUE TITLE
snap version (2016.12) cannot access mounted partitions

### ISSUE THREAD

**Issue by thebucc** [cnr-isti-vclab/meshlab#446] opened 2019-05-07 09:49 UTC
If a partition is mounted, as is the norm, under /mnt or /media, it is invisible to the version of meshlab 2016.12, installed via snap. This seems to be a bug in the snap configuration file snap/snapcraft.yaml: the 'removable-media' interface/plug is missing. 
In fact, any mountpoint outside of /home will fail. This is because /home belongs to a separate interface , 'home', which clearly is added by default.
The required lines should be something like this:
apps:
  meshlab:
    plugs:
      - removable-media
      <other interfaces>

see e.g. https://github.com/videolan/vlc/blob/master/extras/package/snap/snapcraft.yaml#L28

**Comment by hrdkjain** [comment] 2020-09-18 14:27
The same issue with version 2020.07, had to install using `sudo snap install --devmode meshlab`

**Comment by alemuntoni** [comment] 2021-06-15 15:43
duplicate of #466

**Closed by alemuntoni** 2021-06-15 15:43 UTC
