### ISSUE TITLE
meshlab saves invalid STL

### ISSUE THREAD

**Issue by jnweiger** [cnr-isti-vclab/meshlab#372] opened 2018-10-11 17:56 UTC
I am running on Ubuntu 18.04 with

LANG=de_DE.UTF-8
LANGUAGE=de_DE
LC_ALL=de_DE.UTF-8

An STL file saved (binary option not selected) begins like this:
```
solid STL generated by MeshLab
  facet normal -0,000000e+00  0,000000e+00 -1,000000e+00
    outer loop
      vertex   8,787402e+00  1,236925e+01  0,000000e+00
      vertex   8,629922e+00  1,079444e+01  0,000000e+00
      vertex   8,629922e+00  1,236925e+01  0,000000e+00
    endloop
  endfacet
  facet normal -0,000000e+00  0,000000e+00 -1,000000e+00
...
```

All the numeric values use a comma (,) instead of a period(.) -- this is a  syntax error -- even in Germany.

Trivial post processing workaround:
```
tr , . < model.stl > model-fixed.stl
```

**Comment by martin-frbg** [comment] 2018-10-13 13:46
What version of meshlab is that ? This looks a lot like #39, fixed by enforcing "C" locale in #40 (from early 2017, so you would need a more recent build than the "official stable release 2016.12"). FWIW I cannot reproduce it with a build of the current master branch.

**Closed** 2020-07-03 21:44 UTC
Labels: wontfix
