### ISSUE TITLE
Vertex Quality failed

### ISSUE THREAD

**Issue by kiwichrisa** [cnr-isti-vclab/meshlab#1319] opened 2022-10-31 16:18 UTC
Hi
I'm having the same problem, 2020.02 with the following,

Select by Vertex Quality failed: No parameter with name Inclusive found in RichParameterList

[MeshLab problem.pdf](https://github.com/cnr-isti-vclab/meshlab/files/9902878/MeshLab.problem.pdf)

**Comment by zoyt** [comment] 2022-11-01 23:58
Hi,

To my understanding, the "Voronoi Vertex Coloring" filter doesn't effect the vertex quality of a mesh, only the vertex color. 

If you want to select certain faces by color (eg. only the borders), you could use the "Select Faces by color" filter, and use the "Pick Screen Color" function along with the variation sliders to pick out the section that you want. 

Happy to help out if anything else comes up.

OZ

**Comment by alemuntoni** [comment] 2022-11-03 16:16
Duplicate of #1224 
The fix will be available in the next meshlab release (or just download a nightly version).

**Closed by alemuntoni** 2022-11-03 16:16 UTC
