### ISSUE TITLE
HC laplacian filter

### ISSUE THREAD

**Issue by oiluigio** [cnr-isti-vclab/meshlab#510] opened 2019-12-03 16:28 UTC
I am playing with HClaplacian smoothing tool.

Here are two issues:

1- Popup window of HClaplacian tool suggests your algorithm is the same as Vollmer et al. could you specify which are the values you take for alpha and beta from the same publication (alpha is the weight for original points and beta is for previous step points)?

2- It seems that when exporting a mesh in ply after the same filter has been applied a lot of
vertices appear with NaN coordinates, would you confirm that?

Many thanks

**Comment by jmespadero** [comment] 2019-12-04 17:20
FP_HC_LAPLACIAN_SMOOTH is calling to 

tri::Smooth<CMeshO>::VertexCoordLaplacianHC

With value for steps =1

Which you can read at line 552 of file https://github.com/cnr-isti-vclab/vcglib/blob/devel/vcg/complex/algorithms/smooth.h

Beta is 0.5 always. Alpha is not defined.

**Comment by jmespadero** [comment] 2019-12-17 17:23
I can't reproduce your problem with NaN coordinates after applying `HC Laplacian Smooth` several times to a mesh. Can you provide an example that makes the filter fail? Can I propose to close this issue?

![image](https://user-images.githubusercontent.com/6451497/71019019-e0484680-20f9-11ea-93ee-be738e1e723a.png)

**Comment by oiluigio** [comment] 2019-12-17 17:44
The filter never falls! The problem appears when you try to export the
smoothed mesh...
I attach two ply file with the raw mesh that load correctly and the
exported ply after one HC_Laplacian shot.

Concerning the first issue, thanks for sharing the code, would you mean
that alpha=0?
(If the HC_LAPLACIAN is the one detailed by Vollmer et al. and I
understands it correctly alpha must be defined)

Thanks for your help

Giulio

**Comment by jmespadero** [comment] 2019-12-17 17:58
Hi, It is not possible to attach .ply files just answering by email. Please share a link where I can download the file.

**Comment by oiluigio** [comment] 2019-12-17 18:04
raw_ply
https://drive.google.com/open?id=1FhZVEhNas98j74_oAz1VXf3SI7njrblQ

smoothed_play
https://drive.google.com/open?id=1LyGyb8NqysgtUGU2Rch1ZZJ9CTCz4BkS

**Comment by jmespadero** [comment] 2019-12-17 18:45
Bad good news! I can reproduce your problem. 

![image](https://user-images.githubusercontent.com/6451497/71024595-8baac880-2105-11ea-8052-1901f0855395.png)

**Comment by jmespadero** [comment] 2019-12-17 18:50
Problem solved
============

Your input mesh has previous vertex no used by any triangle. Please, apply filter `Cleaning and Repairing` -> `Remove Unreferenced Vertex` before of applying any Smooth Filter.

**Comment by jmespadero** [comment] 2019-12-17 18:53
@cignoni Should we explicit check if a mesh has unreferenced vertex before applying smoothing filters and produce an error if necessary?

**Closed** 2020-01-13 17:32 UTC
