### ISSUE TITLE
meshlabserver: cannot connect to X server

### ISSUE THREAD

**Issue by KrisRoofe** [cnr-isti-vclab/meshlab#211] opened 2017-09-15 09:07 UTC
I use meshlabserver to simplify models for 3D printing on an ubuntu server. As it's a server version of ubuntu, so there is no X installed. 

I want to know how to run meshlabserver without X server.

**Comment by lizarge** [comment] 2018-04-10 12:16
you need use xvfb (apt get install xvfb) in this case,
like this:
$ xvfb-run -a -s "-screen 0 800x600x24" meshlabserver

**Comment by alemuntoni** [comment] 2020-06-20 11:05
Duplicate of #78

**Closed by alemuntoni** 2020-06-20 11:05 UTC
Labels: wontfix
