### ISSUE TITLE
Default build options in linux cause failure

### ISSUE THREAD

**Issue by catskul** [cnr-isti-vclab/meshlab#699] opened 2020-05-29 15:15 UTC
#### Check all platforms you experienced the issue (change to `[x]`)
- [ ] Windows
- [ ] Mac OS
- [x ] Linux
- [ ] Every platform

#### What type of issue is?
- [ ] bug or unexpected behavior
- [ ] crash
- [ ] feature request
- [ x] other (specify...)

#### Describe your issue
Default build fails in ubuntu 18.04 because of default use of in-source build.

qmake (3.1) seems to have a problem with in source builds for some reason which is what `linux_build.sh` and `linux_make_it.sh` do by default. However if an out of source build directory is given, build seems to work without a problem.

error building using default, in source ("../../src") build:
`
cd external/ && ( test -e Makefile || /usr/bin/qmake -o Makefile /home/catskul/opt/meshlab/src/external/external.pro ) && make -f Makefile 
make[1]: Entering directory '/home/catskul/build_meshlab/external'
cd levmar-2.3/ && ( test -e Makefile || /usr/bin/qmake -o Makefile /home/catskul/opt/meshlab/src/external/levmar-2.3/levmar-2.3.pro ) && make -f Makefile 
cd jhead-3.04/ && ( test -e Makefile || /usr/bin/qmake -o Makefile /home/catskul/opt/meshlab/src/external/jhead-3.04/jhead-3.04.pro ) && make -f Makefile 
cd structuresynth-1.5/ && ( test -e Makefile.structuresynth || /usr/bin/qmake -o Makefile.structuresynth /home/catskul/opt/meshlab/src/external/structuresynth-1.5/structuresynth.pro ) && make -f Makefile.structuresynth 
cd muparser_v225/ && ( test -e Makefile.muParser || /usr/bin/qmake -o Makefile.muParser /home/catskul/opt/meshlab/src/external/muparser_v225/muParser.pro ) && make -f Makefile.muParser 
Project ERROR: Unknown module(s) in QT: script
Makefile:99: recipe for target 'sub-structuresynth-1-5-structuresynth-pro-make_first' failed
make[1]: *** [sub-structuresynth-1-5-structuresynth-pro-make_first] Error 3
`

PR forthcoming changing the default.

**Comment by alemuntoni** [comment] 2020-05-29 15:48
Hi, it seems that qmake does not find QtScript, which is strange if the other configuration builds.

Anyhow, this won't be a problem starting from 2020.07 version. We are dropping QtScript and everything that uses it. I've already done it in one of my branches, and it will be merged after June 1st (after 2020.06 release). The branch is [this one](https://github.com/alemuntoni/meshlab/tree/remove_qtscript).

**Comment by alemuntoni** [comment] 2020-05-30 08:08
Just to be sure, could you please check if the first command `cd "${0%/*}"` is working when you run the build script? It works perfectly on github actions, but in some system I saw some errors and it may be the root cause of these problems.

**Closed** 2020-06-19 15:56 UTC
