### ISSUE TITLE
Align mesh

### ISSUE THREAD

**Issue by Perth0s** [cnr-isti-vclab/meshlab#72] opened 2017-02-10 22:40 UTC
Using align mesh for point based gluing both meshes open in alignment window overlapping each other. 
<img width="1456" alt="screen shot 2017-02-10 at 2 39 12 pm" src="https://cloud.githubusercontent.com/assets/25697079/22846885/b9d16cbe-ef9e-11e6-9953-0ece60d7d9a4.png">

**Comment by cignoni** [comment] 2017-02-10 23:12
Duplicate of #30. Already corrected in commit https://github.com/cnr-isti-vclab/meshlab/commit/a68d41beba0e74b11dd1fba2e5569e4fe60bcfa3

**Closed by cignoni** 2017-02-10 23:12 UTC
