### ISSUE TITLE
Import mesh crashed

### ISSUE THREAD

**Issue by wuqi** [cnr-isti-vclab/meshlab#1430] opened 2023-10-12 03:03 UTC
PlatForm: windows 10 x64
Version: v2022.02

When I add a simple glb file as mesh into  meshlab,it crashed,it can be add in blender or windows 3d viewer.

![image](https://github.com/cnr-isti-vclab/meshlab/assets/1532967/4c7cc879-0e44-4d9c-a2c9-d356e4c0bf0d)

the file:
[1.zip](https://github.com/cnr-isti-vclab/meshlab/files/12876581/1.zip)

**Comment by scotgopal** [comment] 2023-11-08 17:06
Potentially a duplicate of https://github.com/cnr-isti-vclab/meshlab/issues/1387

**Comment by alemuntoni** [comment] 2023-11-20 14:18
This has been already solved. The fix will be available in the next version of MeshLab

**Closed by alemuntoni** 2023-11-20 14:18 UTC
