### ISSUE TITLE
crashes when clicking on Repaire non Manifold Edges by splitting vertices

### ISSUE THREAD

**Issue by easterngarden** [cnr-isti-vclab/meshlab#831] opened 2020-11-19 23:28 UTC
#### Check all platforms you experienced the issue (change to `[x]`)
- [x ] Windows
- [ ] Mac OS
- [ ] Linux
- [ ] Every platform

#### What type of issue is?
- [ ] bug or unexpected behavior
- [ x] crash
- [ ] feature request
- [ ] other (specify...)

#### Describe your issue
Whenever I apply the filter "Filters->Cleaning and Repairing->Repaire non Manifold Edges by splitting vertices" onany model meshlab just crashes in RequireVFAdjacency. I use on the latest MeshLab 2020.
...
![image](https://user-images.githubusercontent.com/36804327/99736546-69d76580-2a7b-11eb-9cc1-ef0184b3c967.png)

**Comment by alemuntoni** [comment] 2020-11-20 09:38
Duplicate of #822 
The fix will be available in the next release, or alternatively you can download one of the unofficial prebuilds in the action tab, like [this one](https://github.com/cnr-isti-vclab/meshlab/actions/runs/372702976).

**Closed by alemuntoni** 2020-11-20 09:38 UTC
