### ISSUE TITLE
Align is missing on macOS 2020.12 version!

### ISSUE THREAD

**Issue by elsha13** [cnr-isti-vclab/meshlab#898] opened 2021-01-15 13:27 UTC
Using version 2020.12 on both macos and Windows 10 (via Parallels Desktop)

The mac version does not have the Align tool
Windows version:
<img width="882" alt="Screen Shot 2021-01-15 at 3 25 44 PM" src="https://user-images.githubusercontent.com/42185842/104732481-f766c700-5745-11eb-9f9b-d538a2a0e182.png">

macOS version:
<img width="964" alt="Screen Shot 2021-01-15 at 3 22 02 PM" src="https://user-images.githubusercontent.com/42185842/104732435-e918ab00-5745-11eb-9906-08d0278e6c8d.png">

**Comment by alemuntoni** [comment] 2021-01-21 13:21
Thanks for reporting this!
It is a problem related to the sign of the MacOS version.
In the meantime, MacOS users that need to use the align tool can use the unsigned dmg that can be downloaded from [here](https://github.com/cnr-isti-vclab/meshlab/actions/runs/393797437).

**Comment by martin-pr** [comment] 2021-03-15 21:40
Unfortunately, the problem is still present, and the unsigned dmg is now expired and unavailable. Is there any way around?

**Comment by alemuntoni** [comment] 2021-03-16 09:26
@martin-pr you can download any of the nightly builds available in the github actions tab, like [this one](https://github.com/cnr-isti-vclab/meshlab/actions/runs/654598092).

**Comment by martin-pr** [comment] 2021-03-16 11:28
Thank you! Unfortunately, that dmg doesn't seem to be signed and MacOS will refuse to install it. I've managed to install some of the previous nightly versions, but they suffer from the same problem - missing Align.

**Comment by elsha13** [comment] 2021-03-17 06:25
> @martin-pr you can download any of the nightly builds available in the github actions tab, like [this one](https://github.com/cnr-isti-vclab/meshlab/actions/runs/654598092).

Hi, I was able to download and run this nightly build (portable double). You have to disable the mac's gatekeeper to run the executable. 

Use the following command line to disable gatekeeper: "sudo spctl --master-disable"
Use the following command line to re-enable it when done: "sudo spctl --master-enable"

**Comment by martin-pr** [comment] 2021-03-22 09:45
Thanks a lot! Unfortunately, I am on a work laptop, so disabling gatekeeper is not an option for me. Any chance of getting a new build that includes the Align, and is fully signed?

**Comment by alemuntoni** [comment] 2021-03-22 10:10
Just download one of the previous versions of meshlab. Then you can update it when the next version of meshlab will be released (I still don't know when).

**Comment by alemuntoni** [comment] 2021-05-21 13:00
Align plugin is again available in 2021.05!

**Closed by alemuntoni** 2021-05-21 13:00 UTC
Labels: confirmed
