### ISSUE TITLE
A lot of bugs after update to v2021.05 (Kubuntu 18.04.5 LTS)

### ISSUE THREAD

**Issue by tttmaksko** [cnr-isti-vclab/meshlab#999] opened 2021-05-28 08:55 UTC
Hallo all!

I've used MeshLab for visualization some intermediate calculation (for debugging purposes). Different calculation steps are dumped as a separate layers in Wavefront OBJ geometry format (https://en.wikipedia.org/wiki/Wavefront_.obj_file). So I often use such feature as "reload layer" and "reload all layers". Also I use different visualisation settings for different layers. After update I found the lollowing issues:

1. (may be not bug, but annoying behavior) after reload all layer settings are set to default... and I am obliged to restore all settings manually
2. visibility of vertices and edges are resetted but this is not reflected in layers dialog
3. tool "Get info" selects faces on the layer which is not visible and not selected in layers dialog (I'm not sure, but it may be always first layer...)

Also, I do not know how to change defaults layer visualization params (f.ex. shading and color for faces, edges and vertices; back-face visualization params for faces etc). Is it possible?

**Comment by tttmaksko** [comment] 2021-05-28 10:05
See my update for 3. (I think layer reloading is the actual reason)

How-to-reproduce
1. download and unpack file [faces1.zip](https://github.com/cnr-isti-vclab/meshlab/files/6560082/faces1.zip)
2. create new project in meshlab and import this obj-file to project as layer. (Note: one surface is duplicated -- we should pay attention to it)
3. try to use tool "get info"
4. download and unpack file [faces2.zip](https://github.com/cnr-isti-vclab/meshlab/files/6560083/faces2.zip)
5. replace old file faces_0000007_splt_0.obj with new one
6. in meshlab reload layer
7. try to use tool "get info" again (**it works incorrectly on the duplicated surface**)
8. try to create new project and import second file again.
9. compare it with "reloaded" version (**spoiler: this file doesn't contain duplicated surface**)

**Comment by tttmaksko** [comment] 2021-05-28 10:08
Note: I use the following options for visualization
1. back-face option for faces: **Double**
2. show edges: **on**
3. show vertices: **on**

**Comment by alemuntoni** [comment] 2021-05-28 10:12
Thanks again for the detailed reports, I'll look into them asap!

**Comment by alemuntoni** [comment] 2021-05-31 10:37
Hi, all these three issues should have been resolved in the last commits. They were all related with an uncorrect behaviour related with shading options (and therefore mesh visualization). Could you please try the last nightly build and let me know if issues are solved? 
You can find [here](https://github.com/cnr-isti-vclab/meshlab/wiki/How-to-intall-the-last-nightly) the instructions to download the last nightly.

**Comment by tttmaksko** [comment] 2021-05-31 11:21
> Could you please try the last nightly build and let me know if issues are solved

Super! The issues are fixed! Thnx a lot! :)

BTW, I found one more issue :) It's not very important for me, but may you'll be interesting in it :)

1. create new project and load several layers
2. set all layers invisible except one
3. reload all layers
4. set some invisible layer to visible state (**all layers marked visible (its not true)**)
5. deactivate meshlab main window and activate it again -- **visibility layers marks are set to correct state**

Thanks!

**Comment by alemuntoni** [comment] 2021-07-05 13:15
Hi, sorry for the late reply.
I actually tried the last issue you reported, but I'm not able to reproduce it..

**Closed** 2021-10-31 14:47 UTC
Labels: wontfix, cannot replicate
