### ISSUE TITLE
"xxx.dll does not seem to be a Qt plugin" error when I start meshlab  after build meshlab 

### ISSUE THREAD

**Issue by zxh12345678** [cnr-isti-vclab/meshlab#1510] opened 2024-07-24 06:57 UTC
filter-embree.dll, filter-mesh-alpha_wrap.dll, filter_mesh_booleans.dll 
The above three plugins cannot be loaded.
hope you help me ,thanks
![error](https://github.com/user-attachments/assets/868a5ec0-888d-4a21-aad0-34c4ea240df5)

**Comment by lcb0000** [comment] 2024-08-31 06:17
I had the same problem

**Comment by zxh12345678** [comment] 2024-09-02 08:56
> I had the same problem

you must  put these four dll files in the same folder with meshlab.exe.
![image](https://github.com/user-attachments/assets/674d37cb-a44d-4b39-9998-ea131a0d0cee)

**Comment by alemuntoni** [comment] 2024-09-17 13:59
> > I had the same problem
> 
> you must put these four dll files in the same folder with meshlab.exe. ![image](https://private-user-images.githubusercontent.com/50957628/363624912-674d37cb-a44d-4b39-9998-ea131a0d0cee.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY1ODE2MzgsIm5iZiI6MTcyNjU4MTMzOCwicGF0aCI6Ii81MDk1NzYyOC8zNjM2MjQ5MTItNjc0ZDM3Y2ItYTQ0ZC00YjM5LTk5OTgtZWExMzFhMGQwY2VlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTE3VDEzNTUzOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU0Y2ZhZmYxYmM0YTQxZTYzY2RkYjRhZjM1OWE3OTY1MmM2N2E4ZWUxYTBkYTFiNTg0MTU3OGVlMWFiZDg3ODImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.stim4UOxg903jT17FA4YgZaBmNPonItnD2Ia2tNPkRQ)

These library are already by default in the same folder if meshlab.exe, therefore I assume this issue was caused by some misconfiguration on your installation. Closing this.

**Closed by alemuntoni** 2024-09-17 13:59 UTC

**Comment by lcb0000** [comment] 2024-09-19 09:22
> > I had the same problem
> 
> you must put these four dll files in the same folder with meshlab.exe. ![image](https://private-user-images.githubusercontent.com/50957628/363624912-674d37cb-a44d-4b39-9998-ea131a0d0cee.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY3Mzc4OTYsIm5iZiI6MTcyNjczNzU5NiwicGF0aCI6Ii81MDk1NzYyOC8zNjM2MjQ5MTItNjc0ZDM3Y2ItYTQ0ZC00YjM5LTk5OTgtZWExMzFhMGQwY2VlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTE5VDA5MTk1NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk0ZTlkZGVhZjk0ZjQ4YTZhYWQxOGQzZmE2ZDY3MjU3ODQzYjEyYzE3MjAxNzA4MDg3MzczYTY0YmE5OWJlYzImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.IaEPIyMi-FCeJmMWzAa4b1Mx_dkNW1zKhChUJrkzysw)

I tried the solution you gave, and now there are fewer warnings for starting this software, only:
![image](https://github.com/user-attachments/assets/58c0d094-be51-4481-9d6c-85374e77e277)

**Comment by wu-yi-hong** [comment] 2025-07-18 08:36
So how should this problem be solved?

**Comment by FLOWERCLOUD** [comment] 2026-04-19 03:59
你可以用dependenciesgui 工具来检查 加载失败的dll ,看看是缺了什么dll ， 它是因为缺少了某些dll 就会失败， 我把它缺的dll ，如 vcomp140.dll  拷进去就正常了。
