### ISSUE TITLE
Crash when opening any .ply

### ISSUE THREAD

**Issue by ckgerard** [cnr-isti-vclab/meshlab#586] opened 2020-02-29 22:24 UTC
MeshLab_64bit_fp v2020.02  MacOS High Sierra
Instant Crash when trying to open any .ply file

**Comment by martin-frbg** [comment] 2020-03-01 13:47
Any messages accompanying the crash ? And actually any .ply, or just any created by a particular program ?

**Comment by alemuntoni** [comment] 2020-03-02 09:08
I think this is related to #584.

**Comment by alemuntoni** [comment] 2020-04-09 09:10
Closing this because it is duplicate of #584

**Closed by alemuntoni** 2020-04-09 09:10 UTC
