### ISSUE TITLE
2021.07 crashes (exits) on all texture operations (that I've tried) on Win 10

### ISSUE THREAD

**Issue by ChrisDean** [cnr-isti-vclab/meshlab#1051] opened 2021-08-01 17:39 UTC
I'm combining two meshes (parts of the same total model) by loading the obj and texture of each, flattening layers, and then transferring vertex colours from mesh 1 and mesh 2 to the merged mesh (guided by the you tube video on this).

When I then try to save just the merged texture or save the merged model meshlab dies (exits totally) (I'm saving as obj).

When I check the folder I see the mesh and the mtl file but no texture (which is what I'd expect if something about texturing is causing it to fail).

Both textures are 8192x8192 the merged mesh is about 400k vertices and 3-4m faces

The machine I'm using is a Intel(R) Core(TM) i9-10850K CPU, 32B of RAM and a GeForce RTX 3090 card with win 10 pro.

Any thoughts? Unfortunately I cannot share the meshes.

**Comment by alemuntoni** [comment] 2021-08-02 14:53
Without having the meshes is kind of hard to reproduce and try to solve the issue.
In the last commits I solved some bugs related with textures and transferring, could you please try the [last nightly](https://github.com/cnr-isti-vclab/meshlab/wiki/How-to-install-the-last-nightly-version) and check if the issue is still there? 
Please also share the exact list of operations you perform that cause the crash.

**Closed** 2021-10-15 22:44 UTC
Labels: wontfix, cannot replicate
